### ISSUE TITLE
Crash lors d'un calcul

### ISSUE THREAD

**Issue by Tadraes** [qualitylabs/Yaourt#1]
## Description
Si la zone de saisie est vide et que l'on clique sur "Convertir", l'application crash.

## Idée possible
Ne faire le calcul que lorsque le champ n'est pas vide, afficher un Toast dans le cas contraire.

**Comment by Ironova** [comment]
Erreur réparée, ajout d'un try{} catch(NumberFormatException e){} pour éviter les erreurs dû à un double vide.
